// generated by mBlock5 for mBot
// codes make you happy

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

float distance = 0;
float angle_front = 0;
float angle_right = 0;
float angle_left = 0;
float speed = 0;
float distance_check = 0;
float distance_warn = 0;
float music = 100;
float time = 0.25;
float score = 0;

MeIR ir;

MeRGBLed rgbled_7(7, 2);
MeDCMotor motor_9(9);
MeDCMotor motor_10(10);

void move(int direction, int speed) {
  int leftSpeed = 0;
  int rightSpeed = 0;
  if(direction == 1) {
    leftSpeed = speed;
    rightSpeed = speed;
  } else if(direction == 2) {
    leftSpeed = -speed;
    rightSpeed = -speed;
  } else if(direction == 3) {
    leftSpeed = -speed;
    rightSpeed = speed;
  } else if(direction == 4) {
    leftSpeed = speed;
    rightSpeed = -speed;
  }
  motor_9.run((9) == M1 ? -(leftSpeed) : (leftSpeed));
  motor_10.run((10) == M1 ? -(rightSpeed) : (rightSpeed));
}
MeUltrasonicSensor ultrasonic_3(3);
MeLineFollower linefollower_2(2);
MeBuzzer buzzer;

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

float sigmoid(float freq)
{
     float exp_value;
     float return_value;

     /*** Exponential calculation ***/
     exp_value = exp((double) - freq);

     /*** Final sigmoid value ***/
     return_value = 1 / (1 + exp_value);

     return return_value;
}

void play_winning() {
    buzzer.tone(262, 0.25 * 1000);
    delay(20);
    buzzer.tone(262, 0.25 * 1000);
    delay(20);
    buzzer.tone(392, 0.25 * 1000);
    delay(20);
    buzzer.tone(392, 0.25 * 1000);
    delay(20);
    buzzer.tone(440, 0.25 * 1000);
    delay(20);
    buzzer.tone(440, 0.25 * 1000);
    delay(20);
    buzzer.tone(392, 0.5 * 1000);
    delay(20);
    buzzer.tone(349, 0.25 * 1000);
    delay(20);
    buzzer.tone(349, 0.25 * 1000);
    delay(20);
    buzzer.tone(330, 0.25 * 1000);
    delay(20);
    buzzer.tone(330, 0.25 * 1000);
    delay(20);
    buzzer.tone(294, 0.25 * 1000);
    delay(20);
    buzzer.tone(294, 0.25 * 1000);
    delay(20);
    buzzer.tone(262, 0.5 * 1000);
    delay(20);

    //
      buzzer.tone(392, 0.25 * 1000);
  delay(20);
  buzzer.tone(392, 0.25 * 1000);
  delay(20);
  buzzer.tone(349, 0.25 * 1000);
  delay(20);
  buzzer.tone(349, 0.25 * 1000);
  delay(20);
  buzzer.tone(330, 0.25 * 1000);
  delay(20);
  buzzer.tone(330, 0.25 * 1000);
  delay(20);
  buzzer.tone(294, 0.5 * 1000);
  delay(20);
  buzzer.tone(784, 0.25 * 1000);
  delay(20);
  buzzer.tone(784, 0.25 * 1000);
  delay(20);
  buzzer.tone(698, 0.25 * 1000);
  delay(20);
  buzzer.tone(698, 0.25 * 1000);
  delay(20);
  buzzer.tone(659, 0.25 * 1000);
  delay(20);
  buzzer.tone(659, 0.25 * 1000);
  delay(20);
  buzzer.tone(587, 0.5 * 1000);
  delay(20);

  //
  buzzer.tone(523, 0.25 * 1000);
  delay(20);
  buzzer.tone(523, 0.25 * 1000);
  delay(20);
  buzzer.tone(784, 0.25 * 1000);
  delay(20);
  buzzer.tone(784, 0.25 * 1000);
  delay(20);
  buzzer.tone(880, 0.25 * 1000);
  delay(20);
  buzzer.tone(880, 0.25 * 1000);
  delay(20);
  buzzer.tone(784, 0.5 * 1000);
  delay(20);
  buzzer.tone(698, 0.25 * 1000);
  delay(20);
  buzzer.tone(698, 0.25 * 1000);
  delay(20);
  buzzer.tone(784, 0.25 * 1000);
  delay(20);
  buzzer.tone(784, 0.25 * 1000);
  delay(20);
  buzzer.tone(880, 0.25 * 1000);
  delay(20);
  buzzer.tone(988, 0.25 * 1000);
  delay(20);
  buzzer.tone(1047, 1 * 1000);
  delay(20);
}

void setup() {

  ir.begin();
  while(1) {
      if (time > 0) {
          rgbled_7.setColor(0, #ffffff);
          rgbled_7.show();
      }
      if(ir.keyPressed(70)){
          move(1, 200 / 100.0 * 255);

      }
      if(ir.keyPressed(68)){
          move(3, 100 / 100.0 * 255);

      }
      if(ir.keyPressed(67)){
          move(4, 100 / 100.0 * 255);

      }
      if(ir.keyPressed(21)){
          move(2, 200 / 100.0 * 255);

      }
      if(ir.keyPressed(64)){
          motor_9.run(0);
          motor_10.run(0);

      }
      if(ultrasonic_3.distanceCm() < 5){
          if (time > 0) {
            rgbled_7.setColor(0, #ff0000);
            rgbled_7.show();
            buzzer.tone(music, time * 1000);
            delay(20);
            music += 20;
            time -= 0.005;
            score = sigmoid(music);
          }
          else {
              motor_9.run(0);
              motor_10.run(0);
              rgbled_7.setColor(0, "#00ff15");
              rgbled_7.show();
              buzzer.tone(468, 0.25 * 1000);
              play_winning();
              continue;
          }
      }
      if((0 ? (3 == 0 ? linefollower_2.readSensors() == 0 :
      (linefollower_2.readSensors() & 3) == 3) :
      (3 == 0 ? linefollower_2.readSensors() == 3 :
      (linefollower_2.readSensors() & 3) == 0))) {
      if (time > 0) {
            rgbled_7.setColor(0, #ff0000);
            rgbled_7.show();
            buzzer.tone(music, time * 1000);
            delay(20);
            music += 5;
            time -= 0.001;
            score = sigmoid(music);
          }
          else {
              motor_9.run(0);
              motor_10.run(0);
              rgbled_7.setColor(0, "#00ff15");
              rgbled_7.show();
              buzzer.tone(468, 0.25 * 1000);
              play_winning();
              continue;
          }
  }

      _loop();
  }

}

void _loop() {
  ir.loop();
}

void loop() {
  _loop();
}

